"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { adminDb } from "@/lib/supabase/admin";
import { requireAdmin, requireApproved } from "@/lib/auth";
export async function signOut(){const s=await createClient();await s.auth.signOut();redirect("/")}
export async function createGroup(data:FormData){const user=await requireApproved();const name=String(data.get("name")||"").trim();if(!name)return;const db=adminDb();const {data:group,error}=await db.from("groups").insert({name,created_by:user.id}).select("id").single();if(error)throw new Error(error.message);await db.from("group_members").insert({group_id:group.id,user_id:user.id});redirect(`/groups/${group.id}`)}
export async function addExpense(data:FormData){const user=await requireApproved();const groupId=String(data.get("group_id"));const description=String(data.get("description")||"").trim();const amount=Number(data.get("amount"));if(!description||!Number.isFinite(amount)||amount<=0)return;const s=await createClient();const {data:members}=await s.from("group_members").select("user_id").eq("group_id",groupId);if(!members?.length)return;const {data:expense,error}=await s.from("expenses").insert({group_id:groupId,description,amount,currency:"INR",paid_by:user.id,created_by:user.id}).select("id").single();if(error)throw new Error(error.message);const share=Math.round((amount/members.length)*100)/100;await s.from("expense_splits").insert(members.map((m,i)=>({expense_id:expense.id,user_id:m.user_id,amount:i===members.length-1?Math.round((amount-share*(members.length-1))*100)/100:share})));revalidatePath(`/groups/${groupId}`);revalidatePath("/dashboard")}
export async function settleUp(data:FormData){const user=await requireApproved();const groupId=String(data.get("group_id"));const to=String(data.get("to"));const amount=Number(data.get("amount"));if(!to||!Number.isFinite(amount)||amount<=0)return;const s=await createClient();await s.from("settlements").insert({group_id:groupId,paid_by:user.id,paid_to:to,amount});revalidatePath(`/groups/${groupId}`);revalidatePath("/dashboard")}
export async function addGroupMember(data:FormData){await requireApproved();const groupId=String(data.get("group_id"));const email=String(data.get("email")||"").trim().toLowerCase();if(!email)return;const db=adminDb();const {data:person}=await db.from("profiles").select("id,status").eq("email",email).single();if(!person)throw new Error("That person needs to sign in with Google first.");if(person.status!=="approved")throw new Error("That person has not been approved by an admin yet.");await db.from("group_members").upsert({group_id:groupId,user_id:person.id});revalidatePath(`/groups/${groupId}`)}
export async function updateUser(data:FormData){const actor=await requireAdmin();const id=String(data.get("id"));const action=String(data.get("action"));if(id===actor.id&&(action==="remove"||action==="member"))throw new Error("You cannot remove or demote your own admin account.");const db=adminDb();if(action==="approve")await db.from("profiles").update({status:"approved"}).eq("id",id);if(action==="remove")await db.from("profiles").update({status:"removed",role:"member"}).eq("id",id);if(action==="admin")await db.from("profiles").update({role:"admin",status:"approved"}).eq("id",id);if(action==="member")await db.from("profiles").update({role:"member"}).eq("id",id);revalidatePath("/admin")}
